module.exports = {
    apps: [
        {
            name: 'queue-worker-1',
            namespace: 'app.backend',
            script: 'artisan',
            interpreter: 'php',
            watch: false,
            args: 'queue:work --tries=1 --sleep=3 --timeout=0',
            restart_delay: 1000,
            error_file: './storage/logs/pm2.queue.error.log',
            out_file: './storage/logs/pm2.queue.out.log',
            pid_file: './storage/app/pm2.queue.pid',
        },
        {
            name: 'queue-worker-2',
            namespace: 'app.backend',
            script: 'artisan',
            interpreter: 'php',
            watch: false,
            args: 'queue:work --tries=1 --sleep=3 --timeout=0',
            restart_delay: 1000,
            error_file: './storage/logs/pm2.queue.error.log',
            out_file: './storage/logs/pm2.queue.out.log',
            pid_file: './storage/app/pm2.queue.pid',
        },
        {
            name: 'queue-worker-3',
            namespace: 'app.backend',
            script: 'artisan',
            interpreter: 'php',
            watch: false,
            args: 'queue:work --tries=1 --sleep=3 --timeout=0',
            restart_delay: 1000,
            error_file: './storage/logs/pm2.queue.error.log',
            out_file: './storage/logs/pm2.queue.out.log',
            pid_file: './storage/app/pm2.queue.pid',
        },
        {
            name: 'cron',
            namespace: 'app.backend',
            script: 'artisan',
            interpreter: 'php',
            watch: false,
            args: 'schedule:work',
            restart_delay: 1000,
            error_file: './storage/logs/pm2.cron.error.log',
            out_file: './storage/logs/pm2.cron.out.log',
            pid_file: './storage/app/pm2.cron.pid',
        },
    ],
};
